name: Basic workflow 
on: 
  push:
runs-on: ubuntu-latest
jobs: 
  first-job: 
    

    steps: 
      - name: Hello world print 
        run: echo "Hello, first pipeline"
  second-job:
    steps:
      - name: show time
        needs: first-job 
        run: date