name: Basic workflow 
on: 
  push:
  workflow_dispatch

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Hello world print 
        run: echo "Hello, first pipeline"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job 
    steps:
      - name: show time
        run: date